import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'


const sidebars: SidebarsConfig = {
  docsSidebar: [
    'docs/overview',
    {
      type: 'category',
      label: 'StakeWise Protocol',
      link: {
        type: 'doc',
        id: 'docs/stakewise-protocol/intro',
      },
      items: [
        'docs/stakewise-protocol/understanding-liquid-staking',
        'docs/stakewise-protocol/what-is-stakewise',
        'docs/stakewise-protocol/governance-swise-token',
      ],
    },
    {
      type: 'category',
      label: 'Vaults',
      link: {
        type: 'doc',
        id: 'docs/vaults/intro',
      },
      items: [
        'docs/vaults/how-vaults-work',
        'docs/vaults/customization',
        'docs/vaults/staking-into-a-vault',
        'docs/vaults/vault-performance',
        'docs/vaults/technical-architecture',
      ],
    },
    {
      type: 'category',
      label: 'osToken',
      link: {
        type: 'doc',
        id: 'docs/ostoken/intro',
      },
      items: [
        'docs/ostoken/how-ostoken-works',
      ],
    },
    {
      type: 'category',
      label: 'Oracles',
      link: {
        type: 'doc',
        id: 'docs/oracles/intro',
      },
      items: [
        'docs/oracles/oracle-duties',
      ],
    },
    'docs/fees/intro',
    {
      type: 'category',
      label: 'Governance',
      link: {
        type: 'doc',
        id: 'docs/governance/intro',
      },
      items: [
        'docs/governance/stakewise-dao',
        'docs/governance/dao-treasury',
      ],
    },
    'docs/glossary',

  ],
  guidesSidebar: [
    'docs/guides/intro',
    {
      type: 'category',
      label: 'Staking',
      link: {
        type: 'doc',
        id: 'docs/guides/staking/intro',
      },
      items: [
        'docs/guides/staking/one-click-staking',
        'docs/guides/staking/staking-with-vaults',
        'docs/guides/staking/solo-staking',
        'docs/guides/staking/unstaking',
      ],
    },
    {
      type: 'category',
      label: 'Running a Vault',
      link: {
        type: 'doc',
        id: 'docs/guides/running-a-vault/intro',
      },
      items: [
        'docs/guides/running-a-vault/how-to-create-a-vault',
        'docs/guides/running-a-vault/vault-administration',
        'docs/guides/running-a-vault/getting-your-vault-running',
      ],
    },
    'docs/guides/fee-splitter',
    {
      type: 'category',
      label: 'DeFi',
      link: {
        type: 'doc',
        id: 'docs/guides/defi/intro',
      },
      items: [
        'docs/guides/defi/boost-feature',
      ],
    },
    {
      type: 'category',
      label: 'StakeWise V2',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/guides/stakewise-v2',
        },
      ],
    },
  ],
  contractsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'contracts'
    },
  ],
  sdkSidebar: [
    {
      type: 'autogenerated',
      dirName: 'sdk',
    }
  ]
}


export default sidebars;
