import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'


const sidebars: SidebarsConfig = {
  stakerSidebar: [
    'introduction',
    'rewards',
    'one-click-staking',
    'staking-with-vaults',
    'solo-staking',
    'unstaking',
    {
      type: 'category',
      label: 'DeFi',
      link: {
        type: 'doc',
        id: 'defi/intro',
      },
      items: [
        'defi/how-to-use-boost',
      ],
    },
    {
      type: 'category',
      label: 'StakeWise V2',
      items: [
        {
          type: 'autogenerated',
          dirName: 'stakewise-v2',
        },
      ],
    },
  ],
}


export default sidebars;
