import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'


const sidebars: SidebarsConfig = {
  stakerSidebar: [
    'introduction',
    'rewards',
    'simple-staking',
    'vault-staking',
    'boost',
    'safety',
    {
      type: 'category',
      label: 'StakeWise V2',
      items: [
        {
          type: 'autogenerated',
          dirName: 'stakewise-v2',
        },
      ],
    },
  ],
}


export default sidebars;
