import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'


const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'docs'
    },
  ],
  guidesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'docs/guides'
    },
  ],
  operatorSidebar: [
    {
      type: 'autogenerated',
      dirName: 'operator'
    },
  ],
}


export default sidebars;
