import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  operatorSidebar: [
    'becoming-a-vault-operator',
    'stakewise-vs-native-staking',
    'where-to-start-operator-service',
    'create-your-vault',
    {
      type: 'category',
      label: 'Launch Operator Service V4',
      link: {
        type: 'doc',
        id: 'launch-operator-service/overview',
      },
      items: [
        'launch-operator-service/prerequisites',
        'launch-operator-service/installation',
        'launch-operator-service/validator-keys',
        'launch-operator-service/validators-manager',
        'launch-operator-service/start-operator',
        'launch-operator-service/smoothing-pool-relays',
        'launch-operator-service/node-setup',
      ],
    },
    {
      type: 'category',
      label: 'Manage Your Vault',
      items: [
        'manage-your-vault/vault-administration',
        'manage-your-vault/fee-splitter',
        'manage-your-vault/fee-claiming',
        'manage-your-vault/add-extra-rewards',
        'manage-your-vault/process-metavaults',
        'manage-your-vault/vault-performance',
      ],
    },
    {
      type: 'category',
      label: 'Maintenance',
      items: [
        'maintenance/monitoring',
        'maintenance/rated-network',
        'maintenance/consolidate-validators',
        'maintenance/manual-exit',
        'maintenance/recover-validators',
      ],
    },
    {
      type: 'category',
      label: 'Key Management',
      link: {
        type: 'doc',
        id: 'key-management/index',
      },
      items: [
        'key-management/remote-signer',
        'key-management/hashicorp-vault',
        'key-management/api-mode',
        {
          type: 'category',
          label: 'DVT',
          link: {
            type: 'doc',
            id: 'key-management/dvt/index',
          },
          items: [
            'key-management/dvt/ssv-setup',
            'key-management/dvt/obol-setup',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Operator Service V3',
      link: {
        type: 'doc',
        id: 'operator-service-v3/intro',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'operator-service-v3',
        },
      ],
    },
  ]
}

export default sidebars
