export { default as DocsSections } from './DocsSections/DocsSections'
export { default as BrandAssets } from './BrandAssets/BrandAssets'
export { default as Tooltip } from './Tooltip/Tooltip'
export { default as GitHub } from './GitHub/GitHub'
export { default as Footer } from './Footer/Footer'
export { default as FAQ } from './FAQ/FAQ'
